// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3D5QHY-0W9b9kz1WCGhG2-ep3GsV_feA',
    appId: '1:79194741659:web:3d2c717c03f3c4d9b59f3e',
    messagingSenderId: '79194741659',
    projectId: 'memeoteca-v1',
    authDomain: 'memeoteca-v1.firebaseapp.com',
    storageBucket: 'memeoteca-v1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3wyGjKteyxeCYQvbNj4lH9-1EsNB29_0',
    appId: '1:79194741659:android:c0df01efdd407aa9b59f3e',
    messagingSenderId: '79194741659',
    projectId: 'memeoteca-v1',
    storageBucket: 'memeoteca-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9lqUhE5zjV8x1IXiyc_fhQVtawjYtAWA',
    appId: '1:79194741659:ios:3e71b7dffc97b70fb59f3e',
    messagingSenderId: '79194741659',
    projectId: 'memeoteca-v1',
    storageBucket: 'memeoteca-v1.appspot.com',
    iosBundleId: 'com.example.memeotecav1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9lqUhE5zjV8x1IXiyc_fhQVtawjYtAWA',
    appId: '1:79194741659:ios:3e71b7dffc97b70fb59f3e',
    messagingSenderId: '79194741659',
    projectId: 'memeoteca-v1',
    storageBucket: 'memeoteca-v1.appspot.com',
    iosBundleId: 'com.example.memeotecav1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3D5QHY-0W9b9kz1WCGhG2-ep3GsV_feA',
    appId: '1:79194741659:web:bcce9ef0136ac354b59f3e',
    messagingSenderId: '79194741659',
    projectId: 'memeoteca-v1',
    authDomain: 'memeoteca-v1.firebaseapp.com',
    storageBucket: 'memeoteca-v1.appspot.com',
  );
}
